### PR TITLE
Add Joint Names parameter for customizing joint names in guide settings.

### PR DESCRIPTION
**Pull request by Ruuttu**
This adds a new parameter called "joint_names" to the Main guide class, making it available in all component guides. The parameter allows any skinning joint name to be set in advance in the guide settings. When present, the custom names override default names Shifter would use when creating joints.

Example:

joint_names

We needed this at Remedy where we have content tools and in-game systems relying on specific names for some joints. We think this may be useful for others as well.

### CODE REVIEW

**Comment by miquelcampos** [comment]
Hi @Ruuttu  This is great!  Thanks for the PR. I will test it and merge ASAP!
Funny thing. I was about to implement something similar in this ticket: https://github.com/mgear-dev/shifter/issues/83


....wait !!! What!!!  are you using mGear at Remedy Entertainment!! ?? :D :D

**Comment by Ruuttu** [comment]
Lucky timing I guess! 
We've used mGear successfully for a while at Remedy, but on a small scale. We hope to do much more with it over time :)

There's a problem I discovered with this PR. The new parameter causes old guides to fail import, as in the issue #69. I'll take a look, hopefully it can be fixed.

**Comment by miquelcampos** [comment]
Hello @Ruuttu 

Thanks for checking the number #69 !! :D 
do you know when can you check this one?
If you are not sure, I will do it. Since I want to merge your PR before continue with the naming template in #83 
thanks!

**Comment by Ruuttu** [comment]
Hey, I committed a fix for #69 right here for convenience. It's a suspiciously simple fix tho - hopefully I didn't miss anything.

**Comment by miquelcampos** [comment]
thanks @Ruuttu  I will check and merge tomorrow. :)

**Pull request merged**
