### PR TITLE
Sanity check for synoptic folder existence.

### PR DESCRIPTION
**Pull request by tokejepsen**
This errors the settings out when the folder for the synoptic is non existent.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Should I maybe have versioned up a ```__version__.py``` file and added to a changelog?

**Comment by miquelcampos** [comment]
Hi @tokejepsen 

Interesting!  We don't have ```__version__.py``` file to track versioning.  
How you use it?  We were talking about a similar idea some time ago. We should have a system to track versions in all modules. Now only mgear_dist has versioning

**Comment by tokejepsen** [comment]
Here is an example of how you could setup the versioning; https://github.com/pyblish/pyblish-base/blob/master/pyblish/version.py

You could also have a ```CHANGES``` file; https://github.com/pyblish/pyblish-base/blob/master/CHANGES, but nowadays its more common to just make a release on github like you do with mgear_dist.

If you had versioning of each repository, it might be easier to track changes for when you make a distribution release.

**Comment by miquelcampos** [comment]
We have something similar with Scontruct for mgear_dist
https://github.com/mgear-dev/mgear_dist/blob/master/SConstruct

Lets move this conversation to the Forum and establish the system for all repos

**Pull request merged**
